# alertmanager/config.yml
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'email-notifications'
    repeat_interval: 30m

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'seu-email@exemplo.com'
    from: 'alertmanager@exemplo.com'
    smarthost: 'smtp.exemplo.com:587'
    auth_username: 'seu-usuario-smtp'
    auth_password: 'sua-senha-smtp'
    require_tls: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
