# prometheus/rules/alert.rules.yml
groups:
- name: hosts
  rules:
  - alert: HostHighCpuLoad
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host high CPU load (instance {{ $labels.instance }})"
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host out of memory (instance {{ $labels.instance }})"
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/"}  / node_filesystem_size_bytes{mountpoint="/"} * 100) < 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host out of disk space (instance {{ $labels.instance }})"
      description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: HostHighLoad
    expr: node_load1 > (count by (instance) (node_cpu_seconds_total{mode="idle"}) * 0.8)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host high load (instance {{ $labels.instance }})"
      description: "System load is high\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

- name: containers
  rules:
  - alert: ContainerHighCpuUsage
    expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[1m])) by (name) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container high CPU usage (instance {{ $labels.name }})"
      description: "Container CPU usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: ContainerHighMemoryUsage
    expr: (sum(container_memory_usage_bytes{name!=""}) by (name) / sum(container_memory_max_usage_bytes{name!=""}) by (name) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container high memory usage (instance {{ $labels.name }})"
      description: "Container memory usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

- name: endpoints
  rules:
  - alert: EndpointDown
    expr: probe_success == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Endpoint down (instance {{ $labels.instance }})"
      description: "Endpoint {{ $labels.instance }} is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
